title: Foula Esthetics Academy
description: 低コストでありながら質の高い教育を提供するグローバルアカデミーです。 商材製造会社としての専門的な知識や、世界中のトレンドをいち早く取り入れた最先端のカリキュラムで、次世代のアイリスト育成をサポートします。
baseurl: ""
url: "https://www.foula-academy.com"
keywords: "フーラー フーラストア まつげエクステ 講習, ラッシュリフト セミナー, アイラッシュスクール,
  アイリスト 初心者, まつげ スクール おすすめ, ボリュームラッシュ 技術講習,
  渋谷 まつげ スクール, eyelash academy Tokyo, lash lift seminar Japan"
lang: "ja"
theme: null
exclude:
  - README.md
  - node_modules
include:
  - assets