title: Foula Esthetics Academy
description: "Foula Esthetics Academyの公式サイト"
baseurl: "" 
url: "https://www.foula-academy.com/"  # あなたの GitHub Pages URL
theme: null  # Jekyll のデフォルトテーマを無効化
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
